corpus: corpus_balzac.txt
interfaceLanguage: "Fran\xE7ais.yaml"
language: French.yaml
languageAlterations: false
rules:
  Modify_rule:
    ContoCon_All:
      method: setCheckState
      value: true
      widget: rulesCon_Con_A
    ContoCon_Single:
      method: setCheckState
      value: true
      widget: rulesCon_Con_S
    Delete:
      method: setCheckState
      value: false
      widget: rulesDel
    LettoLet_All:
      method: setCheckState
      value: false
      widget: rulesLet_Let_A
    LettoLet_Single:
      method: setCheckState
      value: false
      widget: rulesLet_Let_S
    Swap:
      method: setCheckState
      value: true
      widget: rulesSwap
    VowtoVow_All:
      method: setCheckState
      value: true
      widget: rulesVow_Vow_A
    VowtoVow_Single:
      method: setCheckState
      value: true
      widget: rulesVow_Vow_S
  Other_rule:
    nbPlayers:
      method: setValue
      value: 3
      widget: rulesNbGrSpin
    nbTurns:
      method: setValue
      value: 10
      widget: rulesTurnSpin
