iconDir: 'icons'
corpusDir: 'corpus'
corpus: 'corpus_balzac.txt'
formats:
- 'xbm'
- 'xpm'
- 'png'
- 'bmp'
- 'gif'
- 'jpg'
- 'jpeg'
- 'pbm'
- 'pgm'
- 'ppm'
languageDir: 
- 'backend'
- 'languages'
language: 'French.yaml'
languageAlterations: True
